### PR TITLE
add data_utils from Sefaria-Data

### PR DESCRIPTION
**Pull request by dimidd**
Motivation:
Cloning Sefaria-Data takes a lot of space, while only the `data_utilities` subdir is needed (specifically `dibur_hamatchil_matcher.py`).
This would make PSHAT more self-sufficient, but the downside is that upstream changes won't be automatically propagated.

Signed-off-by: Dimid Duchovny <dimidd@gmail.com>

### CODE REVIEW

**Comment by nsantacruz** [comment]
I like this idea but the approach is a bit too much. Am I correct that the only dependency on `Sefaria-Data` is `dibur_hamatchil_matcher.py`? Maybe just copy `dibur_hamatchil_matcher.py` into the `PSHAT` repo? It will not allow for upstream changes but I think it's worth that downside.

**Comment by dimidd** [comment]
Yes, only `dibur_hamatchil_matcher.py` and `util.py` are imported, but since it doesn't take much extra space I've added the whole `data_utilities` dir. Anyhow, I can add just these two; your call :)

**Comment by dimidd** [comment]
Ah, I see that `research` is also required for `research.talmud_pos_research.language_classifier.cal_tools`.

**Comment by dimidd** [comment]
Hmm, looks like `research.talmud_pos_research.language_classifier.cal_tools` is very similar to `cal_tools` from PSHAT.

**Comment by nsantacruz** [comment]
I think for this pull request to be reasonable, can you only add `dibur_hamatchil_matcher.py`, `util.py` and decide which `cal_tools.py` is appropriate to include? The rest of the files in this PR should be removed

**Pull request merged**
